"""Export the pydantic contract as JSON Schema and TypeScript types.

The site never hand-writes the shape of ``experiment.json``; it imports the
types emitted here. CI regenerates both artifacts and fails if the checked-in
copies differ, so the two halves of the project cannot drift apart.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from pydantic import TypeAdapter

from .schema import SCHEMA_VERSION, Experiment, Index

BANNER = (
    "// Generated by `compaire schema --export` from src/compaire/schema.py.\n"
    "// Do not edit by hand.\n"
)


def json_schema() -> dict[str, Any]:
    """Both root models under one set of shared ``$defs``."""
    adapter = TypeAdapter(Experiment)
    index_adapter = TypeAdapter(Index)
    exp = adapter.json_schema(ref_template="#/$defs/{model}")
    idx = index_adapter.json_schema(ref_template="#/$defs/{model}")

    defs: dict[str, Any] = {}
    defs.update(exp.pop("$defs", {}))
    defs.update(idx.pop("$defs", {}))
    defs["Experiment"] = exp
    defs["Index"] = idx

    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": "https://github.com/nor0x/compaire/blob/main/docs/experiment.schema.json",
        "title": "CompAIre experiment format",
        "description": f"Schema version {SCHEMA_VERSION}.",
        "$ref": "#/$defs/Experiment",
        "$defs": dict(sorted(defs.items())),
    }


# --- JSON Schema -> TypeScript ------------------------------------------------
# A deliberately small emitter: it only understands the constructs pydantic
# produces for the models in schema.py, and raises on anything else so an
# unsupported field type fails loudly at export time instead of silently
# emitting `any`.


def _ts_type(node: dict[str, Any]) -> str:
    if "$ref" in node:
        return node["$ref"].rsplit("/", 1)[-1]
    if "const" in node:
        return json.dumps(node["const"])
    if "enum" in node:
        return " | ".join(json.dumps(v) for v in node["enum"])
    if "anyOf" in node or "oneOf" in node:
        members = node.get("anyOf") or node["oneOf"]
        return " | ".join(dict.fromkeys(_ts_type(m) for m in members))

    kind = node.get("type")
    if kind == "string":
        return "string"
    if kind in ("number", "integer"):
        return "number"
    if kind == "boolean":
        return "boolean"
    if kind == "null":
        return "null"
    if kind == "array":
        item = _ts_type(node.get("items", {}))
        return f"({item})[]" if " | " in item else f"{item}[]"
    if kind == "object" or "properties" in node:
        extra = node.get("additionalProperties")
        if isinstance(extra, dict):
            return f"Record<string, {_ts_type(extra)}>"
        return "Record<string, unknown>"
    if not node:
        return "unknown"
    raise ValueError(f"cannot express JSON Schema node as TypeScript: {node!r}")


def _ts_interface(name: str, node: dict[str, Any]) -> str:
    if "enum" in node and "properties" not in node:
        return f"export type {name} = {_ts_type(node)};\n"

    required = set(node.get("required", []))
    lines = [f"export interface {name} {{"]
    for prop, spec in node.get("properties", {}).items():
        # A `const` property is the discriminator of a tagged union. TypeScript
        # can only narrow on it when it is non-optional, and pydantic refuses to
        # parse a union member that omits its tag, so every file that passes
        # `compaire validate` really does carry it.
        optional = "" if prop in required or "const" in spec else "?"
        doc = spec.get("description")
        if doc:
            lines.append(f"  /** {doc.strip().splitlines()[0]} */")
        lines.append(f"  {prop}{optional}: {_ts_type(spec)};")
    if node.get("additionalProperties") is True:
        lines.append("  [key: string]: unknown;")
    lines.append("}\n")
    return "\n".join(lines)


def typescript(schema: dict[str, Any] | None = None) -> str:
    schema = schema or json_schema()
    parts = [BANNER, f"export const SCHEMA_VERSION = {SCHEMA_VERSION};\n"]
    for name, node in schema["$defs"].items():
        parts.append(_ts_interface(name, node))
    return "\n".join(parts)


def write(root: Path) -> list[Path]:
    """Write both artifacts, returning the paths that changed on disk."""
    schema = json_schema()
    targets = {
        root / "docs" / "experiment.schema.json": json.dumps(schema, indent=2) + "\n",
        root / "app" / "compaire" / "src" / "lib" / "types.ts": typescript(schema),
    }
    changed = []
    for path, content in targets.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        previous = path.read_text(encoding="utf-8") if path.exists() else None
        if previous != content:
            path.write_text(content, encoding="utf-8", newline="\n")
            changed.append(path)
    return changed
