// Generated by `compaire schema --export` from src/compaire/schema.py.
// Do not edit by hand.

export const SCHEMA_VERSION = 1;

export interface Author {
  name: string;
  github?: string | null;
  url?: string | null;
}

export interface Experiment {
  schema_version?: number;
  id: string;
  title: string;
  description?: string | null;
  author?: Author | null;
  created_at: string;
  updated_at?: string | null;
  view?: "gallery" | "slider" | "table" | "html" | "svg" | "text";
  modality?: "text" | "image";
  tags?: string[];
  prompt: PromptSpec;
  runs?: Run[];
  tool_version?: string | null;
}

export interface HtmlOutput {
  kind: "html";
  path: string;
  bytes?: number | null;
}

export interface ImageOutput {
  kind: "image";
  path: string;
  width?: number | null;
  height?: number | null;
  bytes?: number | null;
  alt?: string | null;
}

export interface Index {
  schema_version?: number;
  generated_at: string;
  experiments?: IndexEntry[];
}

export interface IndexEntry {
  id: string;
  title: string;
  description?: string | null;
  author?: Author | null;
  created_at: string;
  updated_at?: string | null;
  view: "gallery" | "slider" | "table" | "html" | "svg" | "text";
  modality: "text" | "image";
  tags?: string[];
  models?: string[];
  run_count?: number;
  contributors?: number;
  thumb?: string | null;
  total_cost?: number | null;
}

export interface PromptParams {
  temperature?: number | null;
  max_tokens?: number | null;
  top_p?: number | null;
  seed?: number | null;
  [key: string]: unknown;
}

export interface PromptSpec {
  text: string;
  system?: string | null;
  file?: string | null;
  params?: PromptParams;
}

export interface Run {
  id: string;
  model: string;
  model_name?: string | null;
  sample_index?: number;
  status?: "ok" | "error";
  error?: string | null;
  latency_ms?: number | null;
  usage?: Usage | null;
  outputs?: (TextOutput | ImageOutput | HtmlOutput | SvgOutput)[];
  generation_id?: string | null;
  author?: Author | null;
  created_at?: string | null;
}

export interface SvgOutput {
  kind: "svg";
  path: string;
  width?: number | null;
  height?: number | null;
  bytes?: number | null;
  alt?: string | null;
  sanitized?: boolean;
  removed?: string[];
}

export interface TextOutput {
  kind: "text";
  text?: string | null;
  path?: string | null;
  bytes?: number | null;
  format?: "plain" | "markdown";
}

export interface Usage {
  prompt_tokens?: number;
  completion_tokens?: number;
  total_tokens?: number;
  reasoning_tokens?: number | null;
  cost?: number | null;
  [key: string]: unknown;
}
